// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enlngprxmqbkmooaclny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVubG5ncHJ4bXFia21vb2FjbG55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTg2MDcsImV4cCI6MjA2MzkzNDYwN30.FsAcB9yjFNCkg_tXBQJvnDWcB1odgRDG2OWH5Foubtg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);